apiVersion: v1
kind: Service
metadata:
  name: traceassist-backend
  namespace: traceassist
spec:
  selector:
    app: traceassist-backend
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  type: ClusterIP
