apiVersion: v1
kind: Service
metadata:
  name: traceassist-frontend
  namespace: traceassist
spec:
  selector:
    app: traceassist-frontend
  ports:
    - port: 5173
      targetPort: 5173
      name: http
  type: ClusterIP
